// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table Character {
  id SERIAL [primary key]
  userId SERIAL [ref: > User.id, not null]
  campaignId SERIAL [not null]
  level integer, [not null]
  maxHP integer [not null]
  currentHP integer [not null]
  strength integer [not null]
  dexterity integer [not null]
  constitution integer [not null]
  intelligence integer [not null]
  wisdom integer [not null]
  charisma integer [not null]
  race TEXT [not null]
  subrace TEXT [not null]
  heightInches integer [not null]
  weightPounds integer [not null] 
  speed integer [not null]
  isProficientInAcrobatics boolean [not null]
  isProficientInAnimalHandling boolean [not null]
  isProficientInArcana boolean [not null]
  isProficientInAthletics boolean [not null]
  isProficientInDeception boolean [not null]
  isProficientInHistory boolean [not null]
  isProficientInInsight boolean [not null]
  isProficientInIntimidation boolean [not null]
  isProficientInInvestigation boolean [not null]
  isProficientInMedicine boolean [not null]
  isProficientInNature boolean [not null]
  isProficientInPerception boolean [not null]
  isProficientInPerformance boolean [not null]
  isProficientInPersuasion boolean [not null]
  isProficientInReligion boolean [not null]
  isProficientInSleightOfHand boolean [not null]
  isProficientInStealth boolean [not null]
  isProficientInSurvival boolean [not null]
}

Table CharacterItems {
  characterId SERIAL [ref: > Character.id, not null]
  itemId SERIAL [ref: > Item.id, not null]
}

Table CharacterSpells {
  characterId SERIAL [ref: > Character.id, not null]
  spellId SERIAL [ref: > Spell.id, not null]
}

Table CharacterWeapons {
  characterId SERIAL [ref: > Character.id, not null]
  weaponId SERIAL [ref: > Weapon.id, not null]
  isCurrentlyEquipped boolean [not null]
}

Table CharacterArmor {
  characterId SERIAL [ref: > Character.id, not null]
  armorId SERIAL [ref: > Armor.id, not null]
  isCurrentlyEquipped boolean [not null]
}

Table User {
  id SERIAL [primary key]
  username TEXT [not null]
  role TEXT [not null]
  created_at timestamp [not null]
}

enum ROLE {
  DM
  PLAYER
}

Table Role {
  campaignId SERIAL [ref: > Campaign.id, not null]
  userId SERIAL [ref: > User.id, not null]
  role ROLE [not null, note: 'user or dm, controls views the user can access']
}

Table Campaign {
  id SERIAL [primary key]
  name TEXT [not null]
}

Table Encounter {
  id SERIAL [primary key, note: 'prompt DM upon creation']
  totalRounds integer [not null]
  completed boolean [not null]
}

Table Action {
  characterId SERIAL [ref: > Character.id, not null]
  targetId SERIAL [ref: > Character.id, not null]
  encounter SERIAL [ref: > Encounter.id, not null]
}

enum DAMAGE_TYPE {
  ACID
  BLUDGEONING
  COLD
  FIRE
  FORCE
  LIGHTNING
  NECROTIC
  PIERCING
  POISON
  PSYCHIC
  RADIANT
  SLASHING
  THUNDER
}

Table Weapon {
  id SERIAL [primary key]
  name TEXT [not null]
  description text [not null]
  range numeric [not null]
  weight numeric [not null]
  valueCopper integer [not null]
  savingThrowType STAT_TYPE
}

Table Damage {
  id SERIAL [primary key]
  dieSides integer [not null]
  numberOfDice integer [not null]
  damageType DAMAGE_TYPE [not null]
}

Table WeaponDamage {
  weaponId SERIAL [ref: > Weapon.id, not null]
  damageId SERIAL [ref: > Damage.id, not null]
}

enum SPELL_COMPONENT {
  VERBAL
  SOMATIC
  MATERIAL
}

Table Spell {
  id SERIAL [primary key]
  name TEXT [not null]
  description text [not null]
  range numeric [not null]
  minimumLevel integer [not null]
  castingTimeSeconds integer [not null]
  durationSeconds text  [not null]
  requiresConcentration boolean [not null]
  requiresVerbalComponent boolean [not null]
  requiresSomaticComponent boolean [not null]
  requiresMaterialComponent boolean [not null]
  savingThrowType STAT_TYPE
}

Table SpellDamage {
  spellId SERIAL [ref: > Spell.id, not null]
  damageId SERIAL [ref: > Damage.id, not null]
}


enum ARMOR_CATEGORY {
  LIGHT
  MEDIUM
  HEAVY
  SHIELD
}

Table Armor {
  id SERIAL [primary key]
  name TEXT [not null]
  category ARMOR_CATEGORY [not null]
  baseArmorClass integer [not null]
  givesStealthDisadvantage boolean [not null]
  strengthRequirement integer [not null]
  weight numeric [not null]
  valueCopper integer [not null]
}

Table Item {
  id SERIAL [primary key]
  name TEXT [not null]
  description TEXT [not null]
  weight numeric [not null]
  valueCoper integer [not null]
}


Enum STAT_TYPE {
  STRENGTH
  DEXTERITY
  CONSTITUTION
  INTELLIGENCE
  WISDOM
  CHARISMA
}

Table StatEffect {
  id SERIAL [primary key]
  stat STAT_TYPE [not null]
  modifier integer [not null]
}

Table Resistance {
  id SERIAL [primary key]
  stat DAMAGE_TYPE [not null]
  modifier integer [not null]
}

Table CharacterStatEffects {
  characterId SERIAL [not null, ref: > Character.id]
  statEffectId SERIAL [not null, ref: > StatEffect.id]
}

Table CharacterResistances {
  characterId SERIAL [not null, ref: > Character.id]
  resistanceId SERIAL [not null, ref: > Resistance.id]
}