// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table character {
  id SERIAL [primary key]
  userId SERIAL [not null]
  campaignId SERIAL [not null]
  maxHP integer [not null]
  currentHP integer [not null]
  strength integer [not null]
  dexterity integer [not null]
  constitution integer [not null]
  intelligence integer [not null]
  wisdom integer [not null]
  charisma integer [not null]
  race TEXT [not null]
  subrace TEXT [not null]
  heightInches integer [not null]
  weightPounds integer [not null] 
  speed integer [not null]
  isProficientInAcrobatics boolean [not null]
  isProficientInAnimalHandling boolean [not null]
  isProficientInArcana boolean [not null]
  isProficientInAthletics boolean [not null]
  isProficientInDeception boolean [not null]
  isProficientInHistory boolean [not null]
  isProficientInInsight boolean [not null]
  isProficientInIntimidation boolean [not null]
  isProficientInInvestigation boolean [not null]
  isProficientInMedicine boolean [not null]
  isProficientInNature boolean [not null]
  isProficientInPerception boolean [not null]
  isProficientInPerformance boolean [not null]
  isProficientInPersuasion boolean [not null]
  isProficientInReligion boolean [not null]
  isProficientInSleightOfHand boolean [not null]
  isProficientInStealth boolean [not null]
  isProficientInSurvival boolean [not null]
}

Table characterItems {
  characterId SERIAL [ref: > character.id, not null]
  itemId SERIAL [ref: > item.id, not null]
}

Table characterSpells {
  characterId SERIAL [ref: > character.id, not null]
  spellId SERIAL [ref: > spell.id, not null]
}

Table characterWeapons {
  characterId SERIAL [ref: > character.id, not null]
  weaponId SERIAL [ref: > weapon.id, not null]
  isCurrentlyEquipped boolean [not null]
}

Table characterArmor {
  characterId SERIAL [ref: > character.id, not null]
  armorId SERIAL [ref: > armor.id, not null]
  isCurrentlyEquipped boolean [not null]
}

Table user {
  id SERIAL [primary key]
  username TEXT [not null]
  role TEXT [not null]
  created_at timestamp [not null]
}

enum ROLE {
  DM
  PLAYER
}

Table role {
  campaignId SERIAL [ref: > campaign.id, not null]
  userId SERIAL [ref: > user.id, not null]
  role ROLE [not null, note: 'user or dm, controls views the user can access']
}

Table campaign {
  id SERIAL [primary key]
  name TEXT [not null]
}

Table encounter {
  id SERIAL [primary key, note: 'prompt DM upon creation']
  totalRounds integer [not null]
  completed boolean [not null]
}

Table action {
  characterId SERIAL [ref: > character.id, not null]
  targetId SERIAL [ref: > character.id, not null]
  encounter SERIAL [ref: > encounter.id, not null]
}

enum DAMAGE_TYPE {
  ACID
  BLUDGEONING
  COLD
  FIRE
  FORCE
  LIGHTNING
  NECROTIC
  PIERCING
  POISON
  PSYCHIC
  RADIANT
  SLASHING
  THUNDER
}

Table weapon {
  id SERIAL [primary key]
  name TEXT [not null]
  description text [not null]
  range numeric [not null]
  weight numeric [not null]
  valueCopper integer [not null]
  savingThrowType STAT_TYPE
}

Table damage {
  id SERIAL [primary key]
  dieSides integer [not null]
  numberOfDice integer [not null]
  damageType DAMAGE_TYPE [not null]
}

Table weaponDamage {
  weaponId SERIAL [ref: > weapon.id, not null]
  damageId SERIAL [ref: > damage.id, not null]
}

enum SPELL_COMPONENT {
  VERBAL
  SOMATIC
  MATERIAL
}

Table spell {
  id SERIAL [primary key]
  name TEXT [not null]
  description text [not null]
  range numeric [not null]
  minimumLevel integer [not null]
  castingTimeSeconds integer [not null]
  durationSeconds text  [not null]
  requiresConcentration boolean [not null]
  requiresVerbalComponent boolean [not null]
  requiresSomaticComponent boolean [not null]
  requiresMaterialComponent boolean [not null]
  savingThrowType STAT_TYPE
}

Table spellDamage {
  spellId SERIAL [ref: > spell.id, not null]
  damageId SERIAL [ref: > damage.id, not null]
}


enum ARMOR_CATEGORY {
  LIGHT
  MEDIUM
  HEAVY
  SHIELD
}

Table armor {
  id SERIAL [primary key]
  name TEXT [not null]
  category ARMOR_CATEGORY [not null]
  baseArmorClass integer [not null]
  givesStealthDisadvantage boolean [not null]
  strengthRequirement integer [not null]
  weight numeric [not null]
  valueCopper integer [not null]
}

Table item {
  id SERIAL [primary key]
  name TEXT [not null]
  description TEXT [not null]
  weight numeric [not null]
  valueCoper integer [not null]
}


Enum STAT_TYPE {
  STRENGTH
  DEXTERITY
  CONSTITUTION
  INTELLIGENCE
  WISDOM
  CHARISMA
}

Table statEffect {
  id SERIAL [primary key]
  stat STAT_TYPE [not null]
  modifier integer [not null]
}

Table resistance {
  id SERIAL [primary key]
  stat DAMAGE_TYPE [not null]
  modifier integer [not null]
}

Table characterStatEffects {
  characterId SERIAL [not null, ref: > character.id]
  statEffectId SERIAL [not null, ref: > statEffect.id]
}

Table characterResistances {
  characterId SERIAL [not null, ref: > character.id]
  resistanceId SERIAL [not null, ref: > resistance.id]
}